=== Nabisalay/2ndSemester/XML/XML DTD/rrr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT EmployeeData (employee+)>
<!ELEMENT employee (fname,lname,empid,email)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT empid (#PCDATA)>
<!ELEMENT email (#PCDATA)>


<!ATTLIST fname id CDATA '54'>

=== Nabisalay/2ndSemester/XML/XML DTD/dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EmployeeData SYSTEM "rrr.dtd">

    <EmployeeData>
        <employee>
            <fname id='54'>Zahid</fname>
            <lname>Ashraf</lname>
            <empid>231</empid>
            <email>zahid@gmail.com</email>
        </employee>
        <employee >
            <fname id='24'>Amjad</fname>
            <lname>Shareef</lname>
            <empid>422</empid>
            <email>amjad@gmail.com</email>
        </employee>
        <employee>
            <fname id='14'>Sharif</fname>
            <lname>Shahbaz</lname>
            <empid>547</empid>
            <email>sharif@gmail.com</email>
        </employee>
        <employee>
            <fname id='544'>Hina</fname>
            <lname>Ashfaq</lname>
            <empid>541</empid>
            <email>hina@gmail.com</email>
        </employee>
    </EmployeeData>
